web:
  hostname: web-server
  container_name: flask-server
  build: .
  command: python /app/app.py
  ports:
   - "5000:5000"
  links:
   - mysql
   - redis
mysql:
  hostname: mysql-server
  container_name: mysql-db
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: black_bill
redis:
  hostname: redis-server
  container_name: redis-db
  image: redis
  ports:
      - "6379"